### ISSUE TITLE
Restore Files Failing

### ISSUE THREAD

**Issue by ltmichael** [jlesage/docker-cloudberry-backup#28]
When I create a restore plan, it fails with error "Error on process some files".  I have tried restoring multiple different types of files from different backup jobs but it always fails with that same error. 

I am running the latest version on unRaid - I tried looking in the console and log view for any relative errors but do not see any. Can you assist?

edit:
unRaid 6.9.2
CB version 3.3.0.11
Wasabi as Cloud storage

**Comment by jlesage** [comment]
Where are you restoring you files ?  If it's under `/storage`, it doesn't work because by default this directory is read-only for the container.

This can be changed by editing the container's settings.  More specifically, edit the `Storage` setting and change the `Access Mode` to `Read/Write`.  Note that you need to activate the `Advanced View` to be able to edit this setting.

The other solution is to add another read/write `Path` where you can restore your files.

**Comment by ltmichael** [comment]
> 

This was it. Thanks!
